categories:
  - title: "Breaking Changes"
    labels:
      - "breaking change"
  - title: "New Boards"
    collapse-after: 1
    labels:
      - "New Board"
change-template: "- $TITLE #$NUMBER by @$AUTHOR"
template: |
  ## What's Changed

  $CHANGES

  To use in CPython, `pip3 install Adafruit-PlatformDetect`.

  Read the [docs](https://circuitpython.readthedocs.io/projects/platformdetect/en/latest/) for info on how to use it.